steps:
  # Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/portfolio-backend:latest"
      - "."

  # Docker イメージをプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/portfolio-backend:latest"

  # Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "portfolio-backend"
      - "--image=gcr.io/$PROJECT_ID/portfolio-backend:latest"
      - "--platform=managed"
      - "--region=asia-northeast1"
      - "--service-account=spreadsheet-access@pokebros-project.iam.gserviceaccount.com"
      - "--set-env-vars=DEBUG=False,GOOGLE_APPLICATION_CREDENTIALS=/app/my-service-account.json,SPREADSHEET_ID=1OzUHxgBoFz6tzkd3hg4j3L2yeQ5Qw0vk3mIk4j4IjIM"
      - "--cpu=1"
      - "--memory=1Gi"
      - "--timeout=900s"

images:
  - "gcr.io/$PROJECT_ID/portfolio-backend:latest"
